# Generated by Django 4.2.2 on 2023-06-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='version_status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='version',
            new_name='version_number',
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='catalog.product', verbose_name='Продукт'),
        ),
    ]
